name = "annual-summary"
main = "api/questions.js"
compatibility_date = "2023-12-23"
compatibility_flags = ["nodejs_compat"]

[vars]
# 这里不要填写实际的 API key，在 Cloudflare 控制台设置
OPENAI_API_KEY = ""

[[routes]]
pattern = "/api/questions"
script = "api/questions.js"

[[routes]]
pattern = "/api/poster"
script = "api/poster.js"

[build]
command = ""
upload.format = "service-worker"
