name = "annual-summary"
compatibility_date = "2023-12-23"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "."

[build]
command = ""

[[routes]]
pattern = "/api/*"
script = "api/[[route]].js"
